name: Kudos for Code
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  kudos:
    name: Support your open source team
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i
      - uses: LoremLabs/kudos-for-code-action@9cb3a2c82cc49e334628e29e557d56497aabd158
        with:
          search-dir: "."
          destination: "pool"
          pool-id: ""
          setler-keys: ${{ secrets.SETLER_KEYS_0 }}
