name: Kudos for Code
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  kudos:
    name: Support your open source team
    runs-on: ubuntu-latest
    steps:
      - uses: LoremLabs/kudos-for-code-action@0a8536dcb54f675bb86fbf8d3019c3f9370430a1
        with:
          search-dir: "."
          destination: "pool"
          pool-id: ${{ secrets.KUDOS_POOL_ID }}
          setler-keys: ${{ secrets.SETLER_KEYS_0 }}
          pool-storage-token: ${{ secrets.KUDOS_STORAGE_TOKEN }}
