name: Kudos for Code
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  kudos:
    name: Supporting your open source team..
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with: { version: 7 } 
      - uses: LoremLabs/kudos-for-code-action@c1bbab0adfdcf66a2deae7babc36e3dd6a8f914a
        with:
          search-dir: "."
          destination: "pool"
          pool-id: ${{ secrets.KUDOS_POOL_ID }}
          setler-keys: ${{ secrets.SETLER_KEYS_0 }}
          pool-storage-token: ${{ secrets.KUDOS_STORAGE_TOKEN }}
