name: Kudos for Code
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

env:
  KUDOS_STORAGE_TOKEN: KUDOS_STORAGE_TOKEN                   # set this to your preferred AWS region, e.g. us-west-1

jobs:
  kudos:
    name: Support your open source team
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i
      - uses: LoremLabs/kudos-for-code-action@dbe88a51b2d73acdf4d710564a9023142064d3e0
        with:
          search-dir: "."
          destination: "pool"
          pool-id: ""
